return {}
-- return {
--   "Exafunction/codeium.vim",
--   event = "InsertEnter",
--   config = function()
--     vim.keymap.set("i", "<M-i>", function()
--       return vim.fn["codeium#Accept"]()
--     end, { expr = true })
--     vim.keymap.set("i", "<M-]>", function()
--       return vim.fn["codeium#CycleCompletions"](1)
--     end, { expr = true })
--     vim.keymap.set("i", "<M-[>", function()
--       return vim.fn["codeium#CycleCompletions"](-1)
--     end, { expr = true })
--     vim.keymap.set("i", "<M-u>", function()
--       return vim.fn["codeium#Clear"]()
--     end, { expr = true })
--     vim.keymap.set("n", "<leader>ul", function()
--       if vim.g.codeium_enabled == true then
--         vim.cmd("CodeiumDisable")
--       else
--         vim.cmd("CodeiumEnable")
--       end
--     end, { noremap = true, desc = "Toggle Codeium active" })
--   end,
-- }
