return {
  -- {
  --   "folke/noice.nvim",
  --   opts = {
  --     presets = {
  --       lsp_doc_border = true,
  --     },
  --   },
  --   enabled = false,
  -- },
  -- {
  --   "saghen/blink.cmp",
  --   opts = {
  --     appearance = {
  --       use_nvim_cmp_as_default = true,
  --     },
  --     signature = { enabled = true, window = { border = "padded" } },
  --     completion = {
  --       documentation = { window = { border = "rounded" } },
  --       menu = {
  --         border = "rounded",
  --         draw = {
  --           columns = { { "label", "label_description", gap = 1 }, { "kind_icon", "kind" } },
  --         },
  --       },
  --     },
  --   },
  -- },
}
